自动化平台接口:
  公共部分:
      base_url: http://192.168.10.234:8080/at
  基础接口:
    参数查询: /api/autotest/query
    保存步骤输出预期结果: /api/autotest/save/node/expect
    保存步骤输出实际结果: /api/autotest/save/node/result
    保存用例预期结果: /api/autotest/save/expect
    保存用例实际结果: /api/autotest/save/result

微服务平台接口:
  公共部分:
    base_url: http://192.168.9.186/8080
  基础接口:
    登录: /base/sys/login
    新建数据连接: /asset/connect/connectinfo/save
    测试连接: /asset/connect/connectinfo/testConnect
    数据连接-列表查询: /asset/connect/connectinfo/list
    数据连接-删除: /asset/connect/connectinfo/delete
    数据连接-重新隐私发现: /asset/connect/connectinfo/reDiscover

    隐私发现-字段隐私-列表查询: /asset/privacydiscover/resultarrange/page
    隐私发现-字段隐私-隐私统计: /asset/privacydiscover/resultarrange/statistics/{connect_id}
    隐私发现-字段隐私-修改字段隐私类型-单条: /asset/privacydiscover/resultarrange/update
    隐私发现-结构发现-列表查询: /asset/structure/object/page

    隐私发现-发现历史-列表查询: /asset/privacydiscover/historytask/list
    隐私发现-发现历史-差异对比: /asset/privacydiscover/resultcompare/compareresult
    隐私发现-发现历史-本次变化: /asset/privacydiscover/resultcompare/compareresult
    隐私发现-发现历史-错误信息: /asset/privacydiscover/historytask/errorMsg/{connect_id}

    新增字段隐私: /asset/privacyplan/privacyfield/save
    新建隐私类型: /asset/privacytype/save
    新增隐私方案: /asset/privacyplan/privacyplan/save
    隐私方案提交: /asset/privacyplan/privacyplan/submitApproval
    隐私方案审批: /asset/privacyplan/privacyplan/approval



